# Generated by Django 3.0.3 on 2020-03-12 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def insert_roles(apps, schema_editor):
    role = apps.get_model('users', 'Role')
    role(role='gp').save(using=schema_editor.connection.alias)
    role(role='specialist').save(using=schema_editor.connection.alias)
    role(role='anon').save(using=schema_editor.connection.alias)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.RunPython(insert_roles),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=100)),
                ('clinic_address', models.CharField(blank=True, max_length=200)),
                ('clinic_postcode', models.CharField(blank=True, max_length=20)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
