# Generated by Django 3.0.3 on 2020-04-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='clinic_address',
            new_name='clinic_city',
        ),
        migrations.AddField(
            model_name='profile',
            name='clinic_street',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
