# Generated by Django 3.0.3 on 2020-04-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200419_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(default='Dr.', max_length=20),
            preserve_default=False,
        ),
    ]
