#%RAML 1.0
---
title: CranioQ API
version: v0.1

######################
##### Resources #####
######################

/auth:
  /login:
    post:
      description: This endpoint takes credentials and logs in the user if they are correct.
      body:
        application/json:
          example: |
            {
              "email": "john.doe@gmail.com",
              "password": "pass$w0rd"
            }
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "token": "asdkhas6673nasd7dn4n8asd893",
                  "id": 3,
                  "role": "gp"
                }
        400:
          body:
            application/json:
              example: |
                {
                  "error_message": "The email or password provided is incorrect"
                }
        415:
          body:
            application/json:
              example: |
                {
                  "error_message": "Wrong data format."
                }

  /register:
    post:
      description: This enpoint creates a new GP account.
      body:
        application/json:
          example: |
            {
              "email": "john.doe@gmail.com",
              "password": "pass$w0rd",
              "repeat_password": "pass$w0rd",
              "first_name": "John",
              "last_name": "Doe"
            }
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "register_success": true,
                  "displayable_message": "Successfully registered.",
                  "error_message": ""
                }
        415:
          body:
            application/json:
              example: |
                {
                  "error_message": "Wrong data format."
                }

/user:
  /{int:user_id}:
    get:
      description: Fetch the user data of a specific user. The role field can have the following values, "gp", "specialist" or "anon" for a user without a user group.
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id": 1,
                  "email": "john.doe@gmail.com",
                  "first_name": "John",
                  "last_name": "Doe",
                  "role": "specialist"
                }
        404:
          body:
            application/json:
              example: |
                {
                  "error_message": "This user does not exist."
                }

    put:
      description: Updates the user data of a specific user except for his password. This action can only be performed by the user himself or an admin.
      body:
        application/json:
          example: |
            {
              "email": "doe.john@gmail.com",
              "first_name": "John",
              "last_name": "Doe"
            }
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "update_success": true,
                  "displayable_message": "Details changed."
                }
        404:
          body:
            application/json:
              example: |
                {
                  "error_message": "This user does not exist."
                }
        415:
          body:
            application/json:
              example: |
                {
                  "error_message": "Wrong data format."
                }

/questionnaire:
  post:
    description: Add a new questionnaire.
    body:
      application/json:
        example: |
          {
            "patient_id": "123456789"
            "email": "john.doe@gmail.com",
            "agreed": true
          }
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "questionnaire_id": 58
              }
      415:
          body:
            application/json:
              example: |
                {
                  "error_message": "Wrong data format."
                }
