# Generated by Django 3.0.3 on 2020-02-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddIndex(
            model_name='questionnaire',
            index=models.Index(fields=['patient_id'], name='questionnai_patient_991e0d_idx'),
        ),
    ]
