# Generated by Django 3.0.3 on 2020-03-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
