# Generated by Django 3.0.3 on 2020-03-06 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_questionnairetemplate_questiontemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='questionnaires.QuestionnaireTemplate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='templates',
            field=models.ManyToManyField(to='questionnaires.QuestionnaireTemplate'),
        ),
    ]
