# Generated by Django 3.0.3 on 2020-03-06 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0004_auto_20200306_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='questiontemplate',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaires.QuestionTypes'),
        ),
    ]
