# Generated by Django 3.0.3 on 2020-03-06 16:02

from django.db import migrations


def insert_types(apps, schema_editor):
    question_type = apps.get_model('questionnaires', 'QuestionType')
    qt1 = question_type(type='radio')
    qt2 = question_type(type='checkbox')
    qt3 = question_type(type='free_text')
    qt4 = question_type(type='bool')
    qt1.save()
    qt2.save()
    qt3.save()
    qt4.save()


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0005_auto_20200306_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionTypes',
            new_name='QuestionType',
        ),
        migrations.RunPython(insert_types),
    ]
