# Generated by Django 3.0.3 on 2020-03-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0005_auto_20200306_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionTypes',
            new_name='QuestionType',
        ),
    ]
