# Generated by Django 3.0.3 on 2020-03-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0006_auto_20200306_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiontemplate',
            old_name='text',
            new_name='description',
        ),
    ]
