# Generated by Django 3.0.3 on 2020-03-06 16:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0007_auto_20200306_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontemplate',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=10),
        ),
        migrations.AlterField(
            model_name='questiontemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
