# Generated by Django 3.0.3 on 2020-03-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0008_auto_20200306_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnairetemplate',
            old_name='title',
            new_name='name',
        ),
    ]
