# Generated by Django 3.0.3 on 2020-03-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0009_auto_20200307_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairetemplate',
            name='version',
            field=models.CharField(default='0.1', max_length=20),
            preserve_default=False,
        ),
    ]
