# Generated by Django 3.0.3 on 2020-03-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0010_questionnairetemplate_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontemplate',
            name='templates',
        ),
        migrations.AddField(
            model_name='questionnairetemplate',
            name='questions',
            field=models.ManyToManyField(to='questionnaires.QuestionTemplate'),
        ),
    ]
