# Generated by Django 3.0.3 on 2020-03-09 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0012_questioncategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontemplate',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='questionnaires.QuestionCategory'),
            preserve_default=False,
        ),
    ]
