# Generated by Django 3.0.3 on 2020-03-18 10:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0013_questiontemplate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaires.QuestionTemplate')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.Questionnaire')),
            ],
        ),
    ]
