# Generated by Django 3.0.3 on 2020-03-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0014_auto_20200318_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
