# Generated by Django 3.0.3 on 2020-04-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0015_auto_20200330_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='access_id',
            field=models.CharField(default='12345678', max_length=8),
            preserve_default=False,
        ),
    ]
