# Generated by Django 3.0.3 on 2020-04-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0016_questionnaire_access_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='questionnaire',
            name='questionnai_patient_991e0d_idx',
        ),
        migrations.AddIndex(
            model_name='questionnaire',
            index=models.Index(fields=['access_id'], name='questionnai_access__45ec5c_idx'),
        ),
    ]
