# Generated by Django 3.0.3 on 2020-04-06 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0017_auto_20200403_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaires.Questionnaire'),
        ),
    ]
