# Generated by Django 3.0.3 on 2020-04-08 12:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0020_questionnaire_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=10),
        ),
    ]
