# Generated by Django 3.0.3 on 2020-04-08 12:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0021_auto_20200408_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=[], size=10),
        ),
    ]
