# Generated by Django 3.0.3 on 2020-04-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0023_auto_20200408_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='completed',
            new_name='completed_gp',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='completed_guarduian',
            field=models.BooleanField(default=False),
        ),
    ]
