# Generated by Django 3.0.3 on 2020-04-08 12:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0024_auto_20200408_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=10),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='review',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=5),
        ),
    ]
