# Generated by Django 3.0.3 on 2020-04-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0025_auto_20200408_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='completed_guarduian',
            new_name='completed_guardian',
        ),
    ]
