# Generated by Django 3.0.3 on 2020-04-08 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0026_auto_20200408_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
