# Generated by Django 3.0.3 on 2020-04-09 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('questionnaires', '0027_questionnaire_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontemplate',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.Role'),
            preserve_default=False,
        ),
    ]
