# Generated by Django 3.0.3 on 2020-04-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0028_questiontemplate_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='dismiss_notification',
            field=models.BooleanField(default=False),
        ),
    ]
