# Generated by Django 3.0.3 on 2020-04-19 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaires', '0029_questionnaire_dismiss_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='reviewed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
