# Generated by Django 3.0.3 on 2020-04-20 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaires', '0031_auto_20200420_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
