# Generated by Django 3.0.3 on 2020-05-03 18:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0032_auto_20200420_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontemplate',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=10),
        ),
    ]
