# Generated by Django 3.0.3 on 2020-02-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GP',
        ),
    ]
